name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov  # Add other necessary dependencies here
    
    - name: Run tests with pytest
      run: |
        pytest -n auto  # Run tests in parallel using as many CPUs as possible

    - name: Report coverage (optional)
      if: success()
      run: |
        pytest --cov=your_project_directory --cov-report=xml
