name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4  # Du kannst die Anzahl der parallelen Jobs anpassen
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Deine Python-Version hier angeben

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-xdist  # Installiere pytest, pytest-cov und pytest-xdist

      - name: Run tests with pytest
        run: |
          pytest -n auto --cov=./ --cov-report=html  # Tests parallel ausführen und Coverage-Bericht erstellen

