name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-xdist  # Installiere pytest, pytest-cov und pytest-xdist

      - name: Run tests with pytest
        run: |
          pytest -n auto --cov=./ --cov-report=html  # Tests parallel ausführen und Coverage-Bericht erstellen

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
        token: ${{ secrets.CODECOV_TOKEN }}  # dont forget to add this guys
        files: ./coverage.xml
        fail_ci_if_error: true

  security_scan:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Run only on merges to the main branch
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
          python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Snyk for security scanning
          uses: snyk/actions/python@v1.7.0
          with:
            args: --file=requirements.txt  # or Pipfile if applicable
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  # Add this token to your GitHub secrets

build_and_push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/note-api:${{ github.sha }} .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository }}/note-api:${{ github.sha }}